# File: par.py
# Created: 2026-04-26T15:50:46.054715
# Auto-generated by AI System

#!/usr/bin/env python3
"""
par.py - A utility module for parallel processing and task distribution.

This module provides functionality for parallel execution of tasks,
distribution of work across multiple processes or threads, and
management of concurrent operations.
"""

from __future__ import annotations

import concurrent.futures
import functools
import logging
import multiprocessing
import os
import queue
import threading
import time
import types
from concurrent.futures import Future, ThreadPoolExecutor, ProcessPoolExecutor
from typing import (
    Any,
    Callable,
    Dict,
    Iterable,
    List,
    Optional,
    Protocol,
    Set,
    Tuple,
    TypeVar,
    Union,
)

from typing_extensions import TypeAlias

__all__ = [
    "ParallelExecutor",
    "TaskRunner",
    "BatchProcessor",
    "ParallelWorker",
    "TimeoutError",
]

T = TypeVar("T")
R = TypeVar("R")

logger = logging.getLogger(__name__)

class TimeoutError(Exception):
    """Raised when a parallel operation exceeds the specified timeout."""

    pass

class TaskRunner(Protocol[T, R]):
    """Protocol for task runners that execute callable tasks."""

    def run(self, func: Callable[..., R], *args: T.args, **kwargs: T.kwargs) -> R:
        """Execute a task with the given function and arguments."""
        ...

class ParallelExecutor:
    """
    A flexible parallel executor that can use either threads or processes.

    This class provides a unified interface for parallel execution using
    either threading or multiprocessing, with configurable timeout and
    error handling.

    Attributes:
        max_workers: Maximum number of concurrent workers
        use_processes: Whether to use processes instead of threads
        timeout: Default timeout for operations in seconds
    """

    def __init__(
        self,
        max_workers: Optional[int] = None,
        use_processes: bool = False,
        timeout: Optional[float] = None,
    ) -> None:
        """
        Initialize the ParallelExecutor.

        Args:
            max_workers: Maximum number of concurrent workers. If None,
                uses os.cpu_count() or defaults to 4.
            use_processes: If True, use ProcessPoolExecutor; otherwise,
                use ThreadPoolExecutor.
            timeout: Default timeout in seconds for operations.
        """
        self.max_workers = max_workers
        self.use_processes = use_processes
        self.timeout = timeout

        self._executor: Optional[Union[ThreadPoolExecutor, ProcessPoolExecutor]] = None
        self._shutdown = False

    def __enter__(self) -> ParallelExecutor:
        """Context manager entry point."""
        self.start()
        return self

    def __exit__(self, exc_type: Any, exc_val: Any, exc_tb: Any) -> None:
        """Context manager exit point."""
        self.shutdown(wait=True)

    def start(self) -> None:
        """Start the executor."""
        if self._executor is not None:
            raise RuntimeError("Executor already started")

        if self.max_workers is None:
            self.max_workers = (
                multiprocessing.cpu_count()
                if self.use_processes
                else min(32, (os.cpu_count() or 4) * 4)
            )

        if self.use_processes:
            self._executor = ProcessPoolExecutor(max_workers=self.max_workers)
        else:
            self._executor = ThreadPoolExecutor(max_workers=self.max_workers)

    def submit(
        self,
        func: Callable[..., R],
        *args: Any,
        **kwargs: Any,
    ) -> Future[R]:
        """
        Submit a callable to be executed with the given arguments.

        Args:
            func: Callable to execute
            *args: Positional arguments for the callable
            **kwargs: Keyword arguments for the callable

        Returns:
            Future object representing the execution

        Raises:
            RuntimeError: If executor is not started or has been shutdown
        """
        if self._executor is None:
            raise RuntimeError("Executor not started. Call start() first.")
        if self._shutdown:
            raise RuntimeError("Executor has been shutdown")

        return self._executor.submit(func, *args, **kwargs)

    def map(
        self,
        func: Callable[..., R],
        *iterables: Iterable[Any],
        timeout: Optional[float] = None,
        chunksize: int = 1,
    ) -> Iterable[R]:
        """
        Map a function across iterables in parallel.

        Args:
            func: Function to apply to each element
            *iterables: Iterables to map over
            timeout: Timeout for the operation
            chunksize: Number of elements to send to each worker at once

        Returns:
            Iterable of results

        Raises:
            TimeoutError: If operation exceeds timeout
        """
        if self._executor is None:
            raise RuntimeError("Executor not started. Call start() first.")
        if self._shutdown:
            raise RuntimeError("Executor has been shutdown")

        timeout_val = timeout if timeout is not None else self.timeout

        try:
            return self._executor.map(
                func, *iterables, timeout=timeout_val, chunksize=chunksize
            )
        except concurrent.futures.TimeoutError as e:
            raise TimeoutError(f"Parallel map operation timed out: {e}") from e

    def shutdown(self, wait: bool = True, cancel_futures: bool = False) -> None:
        """
        Shutdown the executor.

        Args:
            wait: Wait for pending futures to complete
            cancel_futures: Cancel pending futures
        """
        if self._executor is not None:
            self._executor.shutdown(wait=wait, cancel_futures=cancel_futures)
            self._executor = None
            self._shutdown = True

    def __del__(self) -> None:
        """Destructor to ensure cleanup."""
        self.shutdown(wait=False)

class BatchProcessor:
    """
    Process batches of items in parallel with configurable chunking.

    This class handles large datasets by breaking them into chunks and
    processing each chunk in parallel.

    Attributes:
        chunk_size: Number of items per chunk
        max_workers: Maximum number of parallel workers
        use_processes: Use processes instead of threads
    """

    def __init__(
        self,
        chunk_size: int = 100,
        max_workers: Optional[int] = None,
        use_processes: bool = False,
    ) -> None:
        """
        Initialize the BatchProcessor.

        Args:
            chunk_size: Number of items to process in each chunk
            max_workers: Maximum number of parallel workers
            use_processes: Use processes instead of threads
        """
        self.chunk_size = max(1, chunk_size)
        self.max_workers = max_workers
        self.use_processes = use_processes

    def process(
        self,
        items: Iterable[T],
        processor_func: Callable[[List[T]], List[R]],
        timeout: Optional[float] = None,
    ) -> List[R]:
        """
        Process items in parallel batches.

        Args:
            items: Iterable of items to process
            processor_func: Function that processes a batch of items
            timeout: Timeout for the operation

        Returns:
            List of results from processing each batch

        Raises:
            TimeoutError: If operation exceeds timeout
        """
        with ParallelExecutor(
            max_workers=self.max_workers,
            use_processes=self.use_processes,
            timeout=timeout,
        ) as executor:
            # Convert iterable to list for chunking
            items_list = list(items)
            chunks = [
                items_list[i : i + self.chunk_size]
                for i in range(0, len(items_list), self.chunk_size)
            ]

            futures = [executor.submit(processor_func, chunk) for chunk in chunks]

            results: List[R] = []
            for future in concurrent.futures.as_completed(futures):
                try:
                    results.extend(future.result())
                except Exception as e:
                    logger.error("Error processing batch: %s", e)
                    raise

            return results

class ParallelWorker:
    """
    Worker that processes tasks from a queue in parallel.

    This class manages a pool of workers that process tasks from a
    shared queue. It supports graceful shutdown and error handling.

    Attributes:
        worker_count: Number of worker threads/processes
        use_processes: Use processes instead of threads
        queue_timeout: Timeout for queue operations
    """

    def __init__(
        self,
        worker_count: int = 4,
        use_processes: bool = False,
        queue_timeout: float = 5.0,
    ) -> None:
        """
        Initialize the ParallelWorker.

        Args:
            worker_count: Number of worker threads/processes
            use_processes: Use processes instead of threads
            queue_timeout: Timeout for queue operations in seconds
        """
        self.worker_count = max(1, worker_count)
        self.use_processes = use_processes
        self.queue_timeout = queue_timeout

        self._task_queue: Union[
            queue.Queue[Tuple[Callable[...,